server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings: true
        show_sql: true
        format_sql: true
        hb2dll:
          auto: update
    generate-ddl: true