server:
  port: 8003
  servlet:
    context-path: /orders

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders_service
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings: true
        show_sql: true
        format_sql: true
        hb2dll:
          auto: update
    generate-ddl: true
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 60000
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      acks: "-1"
#      retries: 1
#      properties:
#        enable.idempotence: true
#        max.in.flight.per.connection: 5
#    consumer:
#      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
#      auto-offset-reset: earliest

app:
  services:
    identity: http://localhost:8001/identity
    product: http://localhost:8002/product