server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8001
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2