server:
  port: 8888

app:
  api-prefix: /api/v1
  identity: "http://identity-service:8001/identity"
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    reactor.netty.http.client: DEBUG
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
      routes:
        - id: identity-service
          uri: http://identity-service:8001
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: product-service
          uri: http://product-service:8002
          predicates:
            - Path=${app.api-prefix}/product/**
          filters:
            - StripPrefix=2
        - id: orders-service
          uri: http://orders-service:8003
          predicates:
            - Path=${app.api-prefix}/orders/**
          filters:
            - StripPrefix=2